# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from proto import dockerContainerMgr_pb2 as dockerContainerMgr__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


class DockerContainerMgrServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getContainerIds = channel.unary_unary(
        '/DockerContainerMgrService/getContainerIds',
        request_serializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
        response_deserializer=dockerContainerMgr__pb2.StringList.FromString,
        )
    self.runContainer = channel.unary_unary(
        '/DockerContainerMgrService/runContainer',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=dockerContainerMgr__pb2.ContainerStatus.FromString,
        )
    self.stopContainer = channel.unary_unary(
        '/DockerContainerMgrService/stopContainer',
        request_serializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.startContainer = channel.unary_unary(
        '/DockerContainerMgrService/startContainer',
        request_serializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.getContainerStatus = channel.unary_unary(
        '/DockerContainerMgrService/getContainerStatus',
        request_serializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
        response_deserializer=dockerContainerMgr__pb2.ContainerStatus.FromString,
        )


class DockerContainerMgrServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getContainerIds(self, request, context):
    """获取容器id 列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def runContainer(self, request, context):
    """运行容器
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def stopContainer(self, request, context):
    """停止容器
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def startContainer(self, request, context):
    """启动容器
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getContainerStatus(self, request, context):
    """获取容器状态
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DockerContainerMgrServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getContainerIds': grpc.unary_unary_rpc_method_handler(
          servicer.getContainerIds,
          request_deserializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
          response_serializer=dockerContainerMgr__pb2.StringList.SerializeToString,
      ),
      'runContainer': grpc.unary_unary_rpc_method_handler(
          servicer.runContainer,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=dockerContainerMgr__pb2.ContainerStatus.SerializeToString,
      ),
      'stopContainer': grpc.unary_unary_rpc_method_handler(
          servicer.stopContainer,
          request_deserializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'startContainer': grpc.unary_unary_rpc_method_handler(
          servicer.startContainer,
          request_deserializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'getContainerStatus': grpc.unary_unary_rpc_method_handler(
          servicer.getContainerStatus,
          request_deserializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
          response_serializer=dockerContainerMgr__pb2.ContainerStatus.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'DockerContainerMgrService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
