# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dockerContainerMgr.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='dockerContainerMgr.proto',
  package='com.ices.sh.gspace.rpc',
  syntax='proto3',
  serialized_options=_b('\n\026com.ices.sh.gspace.rpcB\022DockerContainerMgr'),
  serialized_pb=_b('\n\x18\x64ockerContainerMgr.proto\x12\x16\x63om.ices.sh.gspace.rpc\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x19\n\nStringList\x12\x0b\n\x03val\x18\x01 \x03(\t\"\x9e\x01\n\x0f\x43ontainerStatus\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x41\n\x05ports\x18\x03 \x03(\x0b\x32\x32.com.ices.sh.gspace.rpc.ContainerStatus.PortsEntry\x1a,\n\nPortsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\xf4\x03\n\x19\x44ockerContainerMgrService\x12Q\n\x0fgetContainerIds\x12\x1a.google.protobuf.BoolValue\x1a\".com.ices.sh.gspace.rpc.StringList\x12O\n\x0crunContainer\x12\x16.google.protobuf.Empty\x1a\'.com.ices.sh.gspace.rpc.ContainerStatus\x12\x45\n\rstopContainer\x12\x1c.google.protobuf.StringValue\x1a\x16.google.protobuf.Empty\x12G\n\x0fremoveContainer\x12\x1c.google.protobuf.StringValue\x1a\x16.google.protobuf.Empty\x12\x46\n\x0estartContainer\x12\x1c.google.protobuf.StringValue\x1a\x16.google.protobuf.Empty\x12[\n\x12getContainerStatus\x12\x1c.google.protobuf.StringValue\x1a\'.com.ices.sh.gspace.rpc.ContainerStatusB,\n\x16\x63om.ices.sh.gspace.rpcB\x12\x44ockerContainerMgrb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_STRINGLIST = _descriptor.Descriptor(
  name='StringList',
  full_name='com.ices.sh.gspace.rpc.StringList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='val', full_name='com.ices.sh.gspace.rpc.StringList.val', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=138,
)


_CONTAINERSTATUS_PORTSENTRY = _descriptor.Descriptor(
  name='PortsEntry',
  full_name='com.ices.sh.gspace.rpc.ContainerStatus.PortsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='com.ices.sh.gspace.rpc.ContainerStatus.PortsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='com.ices.sh.gspace.rpc.ContainerStatus.PortsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=255,
  serialized_end=299,
)

_CONTAINERSTATUS = _descriptor.Descriptor(
  name='ContainerStatus',
  full_name='com.ices.sh.gspace.rpc.ContainerStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='com.ices.sh.gspace.rpc.ContainerStatus.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='com.ices.sh.gspace.rpc.ContainerStatus.status', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ports', full_name='com.ices.sh.gspace.rpc.ContainerStatus.ports', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CONTAINERSTATUS_PORTSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=299,
)

_CONTAINERSTATUS_PORTSENTRY.containing_type = _CONTAINERSTATUS
_CONTAINERSTATUS.fields_by_name['ports'].message_type = _CONTAINERSTATUS_PORTSENTRY
DESCRIPTOR.message_types_by_name['StringList'] = _STRINGLIST
DESCRIPTOR.message_types_by_name['ContainerStatus'] = _CONTAINERSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StringList = _reflection.GeneratedProtocolMessageType('StringList', (_message.Message,), {
  'DESCRIPTOR' : _STRINGLIST,
  '__module__' : 'dockerContainerMgr_pb2'
  # @@protoc_insertion_point(class_scope:com.ices.sh.gspace.rpc.StringList)
  })
_sym_db.RegisterMessage(StringList)

ContainerStatus = _reflection.GeneratedProtocolMessageType('ContainerStatus', (_message.Message,), {

  'PortsEntry' : _reflection.GeneratedProtocolMessageType('PortsEntry', (_message.Message,), {
    'DESCRIPTOR' : _CONTAINERSTATUS_PORTSENTRY,
    '__module__' : 'dockerContainerMgr_pb2'
    # @@protoc_insertion_point(class_scope:com.ices.sh.gspace.rpc.ContainerStatus.PortsEntry)
    })
  ,
  'DESCRIPTOR' : _CONTAINERSTATUS,
  '__module__' : 'dockerContainerMgr_pb2'
  # @@protoc_insertion_point(class_scope:com.ices.sh.gspace.rpc.ContainerStatus)
  })
_sym_db.RegisterMessage(ContainerStatus)
_sym_db.RegisterMessage(ContainerStatus.PortsEntry)


DESCRIPTOR._options = None
_CONTAINERSTATUS_PORTSENTRY._options = None

_DOCKERCONTAINERMGRSERVICE = _descriptor.ServiceDescriptor(
  name='DockerContainerMgrService',
  full_name='com.ices.sh.gspace.rpc.DockerContainerMgrService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=302,
  serialized_end=802,
  methods=[
  _descriptor.MethodDescriptor(
    name='getContainerIds',
    full_name='com.ices.sh.gspace.rpc.DockerContainerMgrService.getContainerIds',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_wrappers__pb2._BOOLVALUE,
    output_type=_STRINGLIST,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='runContainer',
    full_name='com.ices.sh.gspace.rpc.DockerContainerMgrService.runContainer',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_CONTAINERSTATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='stopContainer',
    full_name='com.ices.sh.gspace.rpc.DockerContainerMgrService.stopContainer',
    index=2,
    containing_service=None,
    input_type=google_dot_protobuf_dot_wrappers__pb2._STRINGVALUE,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='removeContainer',
    full_name='com.ices.sh.gspace.rpc.DockerContainerMgrService.removeContainer',
    index=3,
    containing_service=None,
    input_type=google_dot_protobuf_dot_wrappers__pb2._STRINGVALUE,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='startContainer',
    full_name='com.ices.sh.gspace.rpc.DockerContainerMgrService.startContainer',
    index=4,
    containing_service=None,
    input_type=google_dot_protobuf_dot_wrappers__pb2._STRINGVALUE,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getContainerStatus',
    full_name='com.ices.sh.gspace.rpc.DockerContainerMgrService.getContainerStatus',
    index=5,
    containing_service=None,
    input_type=google_dot_protobuf_dot_wrappers__pb2._STRINGVALUE,
    output_type=_CONTAINERSTATUS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DOCKERCONTAINERMGRSERVICE)

DESCRIPTOR.services_by_name['DockerContainerMgrService'] = _DOCKERCONTAINERMGRSERVICE

# @@protoc_insertion_point(module_scope)
